Comment files

diff --git a/bin-git-extra-commands/git-gitlab-mr b/bin-git-extra-commands/git-gitlab-mr
--- a/bin-git-extra-commands/git-gitlab-mr
+++ b/bin-git-extra-commands/git-gitlab-mr
@@ -24,75 +24,75 @@
 #
 # Note: Has no way of knowing something isn't a GitLab repository.
 
-set -e
+# set -e
 
-havecmd() {
-  [ -n "$(command -v "$@" 2>/dev/null)" ]
-}
+# havecmd() {
+#   [ -n "$(command -v "$@" 2>/dev/null)" ]
+# }
 
-err() {
-  echo "ERR $*" 1>&2
-  exit 1
-}
+# err() {
+#   echo "ERR $*" 1>&2
+#   exit 1
+# }
 
-uriencode() {
-  jq -Rrns --arg in "$*" \
-    '$in|split("\n")|if last == "" then .[:-1] else . end|join(" ")|@uri'
-}
+# uriencode() {
+#   jq -Rrns --arg in "$*" \
+#     '$in|split("\n")|if last == "" then .[:-1] else . end|join(" ")|@uri'
+# }
 
-if ! havecmd jq; then
-  err 'Required program missing: jq'
-fi
+# if ! havecmd jq; then
+#   err 'Required program missing: jq'
+# fi
 
-ref="$(git rev-parse --abbrev-ref --symbolic-full-name @{u})"
-if [ -z "$ref" ]; then
-  err "No upstream for branch: $(git rev-parse --abbrev-ref --symbolic-full-name @)"
-fi
-repo="${ref%%/*}"
-if [ -z "$repo" ]; then
-  err "Unable to determine repository for ref: $ref"
-fi
-branch="${ref#$repo/}"
-if [ -z "$branch" ]; then
-  err "Unable to determine ref in repository of ref: $ref"
-fi
-uri="$(git remote get-url "$repo")"
-if [ -z "$uri" ]; then
-  err "Unable to determine URI of repository: $repo"
-fi
+# ref="$(git rev-parse --abbrev-ref --symbolic-full-name @{u})"
+# if [ -z "$ref" ]; then
+#   err "No upstream for branch: $(git rev-parse --abbrev-ref --symbolic-full-name @)"
+# fi
+# repo="${ref%%/*}"
+# if [ -z "$repo" ]; then
+#   err "Unable to determine repository for ref: $ref"
+# fi
+# branch="${ref#$repo/}"
+# if [ -z "$branch" ]; then
+#   err "Unable to determine ref in repository of ref: $ref"
+# fi
+# uri="$(git remote get-url "$repo")"
+# if [ -z "$uri" ]; then
+#   err "Unable to determine URI of repository: $repo"
+# fi
 
-scheme=https
-suffix="/merge_requests/new?$(uriencode 'merge_request[source_branch]')=$(uriencode "${branch}")"
-case "$uri" in
-*@*:*)     # SSH
-  uri="${uri#*@}"
-  domain="${uri%:*}"
-  path="/${uri#${domain}:}"
-  ;;
-https://*) # HTTPS
-  uri="${uri#https://}"
-  uri="${uri#*@}"
-  domain="${uri%%/*}"
-  path="${uri#${domain}}"
-  ;;
-http://*)  # HTTP?
-  scheme=http # Why? Why do this?
-  uri="${uri#https://}"
-  uri="${uri#*@}"
-  domain="${uri%%/*}"
-  path="${uri#${domain}}"
-  ;;
-*)
-  err "Unrecognized URI: $uri"
-  ;;
-esac
+# scheme=https
+# suffix="/merge_requests/new?$(uriencode 'merge_request[source_branch]')=$(uriencode "${branch}")"
+# case "$uri" in
+# *@*:*)     # SSH
+#   uri="${uri#*@}"
+#   domain="${uri%:*}"
+#   path="/${uri#${domain}:}"
+#   ;;
+# https://*) # HTTPS
+#   uri="${uri#https://}"
+#   uri="${uri#*@}"
+#   domain="${uri%%/*}"
+#   path="${uri#${domain}}"
+#   ;;
+# http://*)  # HTTP?
+#   scheme=http # Why? Why do this?
+#   uri="${uri#https://}"
+#   uri="${uri#*@}"
+#   domain="${uri%%/*}"
+#   path="${uri#${domain}}"
+#   ;;
+# *)
+#   err "Unrecognized URI: $uri"
+#   ;;
+# esac
 
-: "${mrurl:=${scheme}://${domain}${path%.git}${suffix}}"
-if havecmd open; then
-  open "$mrurl"
-elif havecmd xdg-open; then
-  xdg-open "$mrurl" >/dev/null 2>&1
-else
-  # Print URL if we can't open it
-  echo "$mrurl"
-fi
+# : "${mrurl:=${scheme}://${domain}${path%.git}${suffix}}"
+# if havecmd open; then
+#   open "$mrurl"
+# elif havecmd xdg-open; then
+#   xdg-open "$mrurl" >/dev/null 2>&1
+# else
+#   # Print URL if we can't open it
+#   echo "$mrurl"
+# fi
diff --git a/bin-git-extra-commands/git-rebase-theirs b/bin-git-extra-commands/git-rebase-theirs
--- a/bin-git-extra-commands/git-rebase-theirs
+++ b/bin-git-extra-commands/git-rebase-theirs
@@ -18,113 +18,113 @@
 #    along with this program. If not see <http://www.gnu.org/licenses/gpl.html>
 
 #Defaults:
-verbose=0
-backup=1
-inplace=0
-ext=".bak"
+# verbose=0
+# backup=1
+# inplace=0
+# ext=".bak"
 
-message() { printf "%s\n" "$1" >&2 ; }
-# shellcheck disable=SC2104
-skip()    { message "skipping ${2:-$file}${1:+: $1}"; continue ; }
-argerr()  { printf "%s: %s\n" "$myname" "${1:-error}" >&2 ; usage 1 ; }
-invalid() { argerr "invalid option: $1" ; }
-missing() { argerr "missing${1:+ $1} operand." ; }
+# message() { printf "%s\n" "$1" >&2 ; }
+# # shellcheck disable=SC2104
+# skip()    { message "skipping ${2:-$file}${1:+: $1}"; continue ; }
+# argerr()  { printf "%s: %s\n" "$myname" "${1:-error}" >&2 ; usage 1 ; }
+# invalid() { argerr "invalid option: $1" ; }
+# missing() { argerr "missing${1:+ $1} operand." ; }
 
-usage() {
-	cat <<- USAGE
-	Usage: $myname [options] [--] FILE...
-	USAGE
-	if [[ "$1" ]] ; then
-		cat >&2 <<- USAGE
-		Try '$myname --help' for more information.
-		USAGE
-		exit 1
-	fi
-	cat <<-USAGE
+# usage() {
+# 	cat <<- USAGE
+# 	Usage: $myname [options] [--] FILE...
+# 	USAGE
+# 	if [[ "$1" ]] ; then
+# 		cat >&2 <<- USAGE
+# 		Try '$myname --help' for more information.
+# 		USAGE
+# 		exit 1
+# 	fi
+# 	cat <<-USAGE
 
-	Resolve git rebase conflicts in FILE(s) by favoring 'theirs' version
+# 	Resolve git rebase conflicts in FILE(s) by favoring 'theirs' version
 
-	When using git rebase, conflicts are usually wanted to be resolved
-	by favoring the <working branch> version (the branch being rebased,
-	'theirs' side in a rebase), instead of the <upstream> version (the
-	base branch, 'ours' side)
+# 	When using git rebase, conflicts are usually wanted to be resolved
+# 	by favoring the <working branch> version (the branch being rebased,
+# 	'theirs' side in a rebase), instead of the <upstream> version (the
+# 	base branch, 'ours' side)
 
-	But git rebase --strategy -X theirs is only available from git 1.7.3
-	For older versions, $myname is the solution. And Despite the name,
-	it's also useful for fixing failed cherry-picks
+# 	But git rebase --strategy -X theirs is only available from git 1.7.3
+# 	For older versions, $myname is the solution. And Despite the name,
+# 	it's also useful for fixing failed cherry-picks
 
-	It works by discarding all lines between '<<<<<<< ' and '========'
-	inclusive, and also the the '>>>>>> commit' marker.
+# 	It works by discarding all lines between '<<<<<<< ' and '========'
+# 	inclusive, and also the the '>>>>>> commit' marker.
 
-	By default it outputs to stdout, but files can be edited in-place
-	using --in-place, which, unlike sed, creates a backup by default.
+# 	By default it outputs to stdout, but files can be edited in-place
+# 	using --in-place, which, unlike sed, creates a backup by default.
 
-	Options:
-	  -h|--help            show this page.
-	  -v|--verbose         print more details in stderr.
+# 	Options:
+# 	  -h|--help            show this page.
+# 	  -v|--verbose         print more details in stderr.
 
-	  --in-place[=SUFFIX]  edit files in place, creating a backup with
-	                       SUFFIX extension. Default if blank is "$ext"
+# 	  --in-place[=SUFFIX]  edit files in place, creating a backup with
+# 	                       SUFFIX extension. Default if blank is "$ext"
 
-	  --no-backup          disables backup
+# 	  --no-backup          disables backup
 
-	Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
-	License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
-	USAGE
-	exit 0
-}
-myname="${0##*/}"
+# 	Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
+# 	License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
+# 	USAGE
+# 	exit 0
+# }
+# myname="${0##*/}"
 
-# Option handling
-files=()
-while (( $# )); do
-	case "$1" in
-	-h|--help     ) usage            ;;
-	-v|--verbose  ) verbose=1        ;;
-	--no-backup   ) backup=0         ;;
-	--in-place    ) inplace=1        ;;
-	--in-place=*  ) inplace=1
-	                suffix="${1#*=}" ;;
-	--            ) shift ; break    ;;
-	-*            ) invalid "$1"     ;;
-	*             ) files+=( "$1" )  ;;
-	esac
-	shift
-done
-files+=( "$@" )
+# # Option handling
+# files=()
+# while (( $# )); do
+# 	case "$1" in
+# 	-h|--help     ) usage            ;;
+# 	-v|--verbose  ) verbose=1        ;;
+# 	--no-backup   ) backup=0         ;;
+# 	--in-place    ) inplace=1        ;;
+# 	--in-place=*  ) inplace=1
+# 	                suffix="${1#*=}" ;;
+# 	--            ) shift ; break    ;;
+# 	-*            ) invalid "$1"     ;;
+# 	*             ) files+=( "$1" )  ;;
+# 	esac
+# 	shift
+# done
+# files+=( "$@" )
 
-if ! (( "${#files[@]}" )); then missing "FILE"; fi
+# if ! (( "${#files[@]}" )); then missing "FILE"; fi
 
-ext=${suffix:-$ext}
+# ext=${suffix:-$ext}
 
-for file in "${files[@]}"; do
+# for file in "${files[@]}"; do
 
-	if ! [[ -f "$file" ]]; then skip "not a valid file"; fi
+# 	if ! [[ -f "$file" ]]; then skip "not a valid file"; fi
 
-	if ((inplace)); then
-		outfile=$(mktemp) || skip "could not create temporary file"
-		# shellcheck disable=SC2064
-		trap "rm -f -- '$outfile'" EXIT
-		cp "$file" "$outfile" || skip
-		exec 3>"$outfile"
-	else
-		exec 3>&1
-	fi
+# 	if ((inplace)); then
+# 		outfile=$(mktemp) || skip "could not create temporary file"
+# 		# shellcheck disable=SC2064
+# 		trap "rm -f -- '$outfile'" EXIT
+# 		cp "$file" "$outfile" || skip
+# 		exec 3>"$outfile"
+# 	else
+# 		exec 3>&1
+# 	fi
 
-	# Do the magic :)
-	awk '/^<<<<<<<+ .+$/,/^=+$/{next} /^>>>>>>>+ /{next} 1' "$file" >&3
+# 	# Do the magic :)
+# 	awk '/^<<<<<<<+ .+$/,/^=+$/{next} /^>>>>>>>+ /{next} 1' "$file" >&3
 
-	exec 3>&-
+# 	exec 3>&-
 
-	if ! ((inplace)); then continue; fi
+# 	if ! ((inplace)); then continue; fi
 
-	diff "$file" "$outfile" >/dev/null && skip "no conflict markers found"
+# 	diff "$file" "$outfile" >/dev/null && skip "no conflict markers found"
 
-	if ((backup)); then cp "$file" "$file$ext" || skip "could not backup"; fi
+# 	if ((backup)); then cp "$file" "$file$ext" || skip "could not backup"; fi
 
-	cp "$outfile" "$file" || skip "could not edit in-place"
-	rm -f -- "$outfile"
-	trap - EXIT
+# 	cp "$outfile" "$file" || skip "could not edit in-place"
+# 	rm -f -- "$outfile"
+# 	trap - EXIT
 
-	if ((verbose)); then message "resolved ${file}"; fi
-done
+# 	if ((verbose)); then message "resolved ${file}"; fi
+# done
diff --git a/bin-git-extra-commands/git-submodule-rm b/bin-git-extra-commands/git-submodule-rm
--- a/bin-git-extra-commands/git-submodule-rm
+++ b/bin-git-extra-commands/git-submodule-rm
@@ -13,46 +13,46 @@
 #     https://stackoverflow.com/a/7646931
 #     https://stackoverflow.com/a/16162000
 
-set -eu
+# set -eu
 
-if [[ $# -eq 0 ]]; then
-  echo 'Usage: git submodule-rm <path ...>' >&2
-  exit 2
-fi
+# if [[ $# -eq 0 ]]; then
+#   echo 'Usage: git submodule-rm <path ...>' >&2
+#   exit 2
+# fi
 
-if [[ ! -f .gitmodules ]]; then
-  echo 'Run this from the root of your repo which must have a .gitmodules file.' >&2
-  exit 1
-fi
+# if [[ ! -f .gitmodules ]]; then
+#   echo 'Run this from the root of your repo which must have a .gitmodules file.' >&2
+#   exit 1
+# fi
 
-if [[ ! -w .gitmodules ]]; then
-  echo '.gitmodules file is not writable for the current user.' >&2
-  exit 1
-fi
+# if [[ ! -w .gitmodules ]]; then
+#   echo '.gitmodules file is not writable for the current user.' >&2
+#   exit 1
+# fi
 
-for path in "$@"; do
-  submodule_path="${path%/}"
+# for path in "$@"; do
+#   submodule_path="${path%/}"
 
-  if [[ -z "$(git config --file=.gitmodules "submodule.${submodule_path}.url")" ]]; then
-    echo "Submodule '$submodule_path' not found." >&2
-    continue
-  fi
+#   if [[ -z "$(git config --file=.gitmodules "submodule.${submodule_path}.url")" ]]; then
+#     echo "Submodule '$submodule_path' not found." >&2
+#     continue
+#   fi
 
-  if [[ ! -w "$submodule_path" ]]; then
-    echo "Submodule path '$submodule_path' is not writable." >&2
-    continue
-  fi
+#   if [[ ! -w "$submodule_path" ]]; then
+#     echo "Submodule path '$submodule_path' is not writable." >&2
+#     continue
+#   fi
 
-  # If any of the following commands fail it's probably because the repo
-  # was already in a corrupted state and we can't do anything to handle
-  # that anyway so we just let the entire script crash.
+#   # If any of the following commands fail it's probably because the repo
+#   # was already in a corrupted state and we can't do anything to handle
+#   # that anyway so we just let the entire script crash.
 
-  git submodule --quiet deinit --force "$submodule_path"
-  rmdir "$submodule_path"
-  git rm --cached -rfq "$submodule_path"
+#   git submodule --quiet deinit --force "$submodule_path"
+#   rmdir "$submodule_path"
+#   git rm --cached -rfq "$submodule_path"
 
-  git config -f .gitmodules --remove-section "submodule.$submodule_path"
-  rm -rf ".git/modules/$submodule_path"
+#   git config -f .gitmodules --remove-section "submodule.$submodule_path"
+#   rm -rf ".git/modules/$submodule_path"
 
-  git add .gitmodules
-done
+#   git add .gitmodules
+# done
